# Generated by Django 3.2.13 on 2022-07-28 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0004_question_question_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeVoting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("time_voting", models.DateTimeField()),
                ("question", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="project.question")),
                ("users", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
